const wordsList = [
    // 第一部分：人物关系
    { english: "friend", chinese: "朋友" },
    { english: "boy", chinese: "男孩" },
    { english: "girl", chinese: "女孩" },
    { english: "mother", chinese: "母亲" },
    { english: "father", chinese: "父亲" },
    { english: "sister", chinese: "姐妹" },
    { english: "brother", chinese: "兄弟" },
    { english: "uncle", chinese: "叔叔；舅舅" },
    { english: "man", chinese: "男人" },
    { english: "woman", chinese: "女人" },
    
    // 第二部分：衣服
    { english: "jacket", chinese: "夹克衫" },
    { english: "shirt", chinese: "衬衫" },
    { english: "T-shirt", chinese: "T恤衫" },
    { english: "skirt", chinese: "短裙" },
    { english: "dress", chinese: "连衣裙" },
    { english: "jeans", chinese: "牛仔裤" },
    { english: "sweater", chinese: "毛衣" },
    { english: "coat", chinese: "上衣" },
    { english: "raincoat", chinese: "雨衣" },
    { english: "shorts", chinese: "短裤" },
    { english: "sneakers", chinese: "网球鞋" },
    { english: "slippers", chinese: "拖鞋" },
    { english: "sandals", chinese: "凉鞋" },
    { english: "boots", chinese: "靴子" },
    { english: "hat", chinese: "帽子" },
    { english: "cap", chinese: "便帽" },
    { english: "sunglasses", chinese: "太阳镜" },
    { english: "tie", chinese: "领带" },
    { english: "scarf", chinese: "围巾" },
    { english: "gloves", chinese: "手套" },

    // 第三部分：学习用品
    { english: "pen", chinese: "钢笔" },
    { english: "pencil", chinese: "铅笔" },
    { english: "ruler", chinese: "尺子" },
    { english: "book", chinese: "书" },
    { english: "bag", chinese: "包" },
    { english: "pencil-case", chinese: "铅笔盒" },
    { english: "schoolbag", chinese: "书包" },
    { english: "eraser", chinese: "橡皮" },
    { english: "crayon", chinese: "蜡笔" },
    { english: "notebook", chinese: "笔记本" },

    // 第四部分：动物
    { english: "cat", chinese: "猫" },
    { english: "dog", chinese: "狗" },
    { english: "pig", chinese: "猪" },
    { english: "duck", chinese: "鸭" },
    { english: "rabbit", chinese: "兔子" },
    { english: "horse", chinese: "马" },
    { english: "elephant", chinese: "大象" },
    { english: "fish", chinese: "鱼" },
    { english: "bird", chinese: "鸟" },
    { english: "monkey", chinese: "猴子" }
];
